"""
preflight_check.py
==================
Pre-flight validation for POs already in the pipeline.

Reads the latest enriched JSONL output (after extraction + mapping) and
checks EVERY PO for readiness before any SAP Sales Order is created.

A PO is SAFE TO SUBMIT only if ALL of these pass:
  1. Customer (sold-to) is resolved with high confidence (>= 0.70)
  2. Ship-to party is resolved (not blank / not fallback)
  3. ALL line items have a valid internal_material_number (no unmapped mats)
  4. ALL quantities are > 0 and units are valid
  5. Sales Org is present
  6. At least 1 Sales Order was generated by the mapper

Usage:
    python preflight_check.py
    python preflight_check.py --input results_outlook_po_extracted_enriched.jsonl
    python preflight_check.py --threshold 0.75
    python preflight_check.py --json-report preflight_report.json

Exit code:
    0  -- All POs are SAFE (or none with issues)
    1  -- One or more POs have FAIL issues (would route to exception)
"""

import sys
import os
import json
import argparse
from pathlib import Path
from datetime import datetime

sys.stdout.reconfigure(encoding="utf-8")

# ── Config ────────────────────────────────────────────────────────────────────
DEFAULT_INPUT   = "results_outlook_po_extracted_enriched.jsonl"
MIN_CONFIDENCE  = 0.70   # minimum customer match confidence to be safe
VALID_UNITS     = {
    # ISO / SAP standard
    "KG", "KGM", "G", "GRM", "TO", "TNE", "MT", "LB", "LBR", "OZ", "T", "ST", "LT",
    # Language variants commonly seen in POs
    "KILOGRAMM", "KILOGRAM", "KILOGRAMS", "KILOGRAMME",   # DE/EN variants
    "KGS", "KGS.", "KG.", "KG,",                          # abbreviation variants
    "吨", "噸", "公吨", "公噸",                             # Chinese units
}
SAFE_COLOR   = "\033[92m"   # green
WARN_COLOR   = "\033[93m"   # yellow
FAIL_COLOR   = "\033[91m"   # red
RESET_COLOR  = "\033[0m"

def color(text, code):
    return f"{code}{text}{RESET_COLOR}"

def validate_po(obj: dict, min_confidence: float) -> dict:
    """
    Validate a single enriched PO record.
    Returns a result dict with status 'OK' | 'WARNING' | 'FAIL'.
    """
    issues   = []
    warnings = []

    hdr     = obj.get("header_fields") or {}
    sos     = obj.get("sales_orders")  or []
    src     = obj.get("source_file", "?")
    po_num  = hdr.get("po_number") or hdr.get("customer_po_number") or "?"
    cust_id = (hdr.get("customer_number") or hdr.get("sold_to_id") or "").strip()
    cust_nm = (hdr.get("customer_name_matched") or hdr.get("customer_name") or "?")
    sorg    = None

    # ── 1. No sales orders generated at all ──────────────────────────────────
    if not sos:
        issues.append("No Sales Order generated — customer/material could not be mapped")
        return {
            "status": "FAIL", "po_number": po_num, "source_file": src,
            "customer_id": cust_id, "customer_name": cust_nm,
            "ship_to_id": "", "ship_to_name": "", "sales_org": "",
            "n_sos": 0, "n_items": 0, "n_unmapped": 0, "confidence": None,
            "issues": issues, "warnings": warnings,
        }

    # ── 2. Customer confidence ────────────────────────────────────────────────
    conf = hdr.get("customer_confidence")
    if conf is None:
        val = hdr.get("validation") or {}
        conf = val.get("confidence")
    if conf is not None:
        conf = float(conf)
        if conf < min_confidence:
            issues.append(
                f"Low customer match confidence: {conf:.0%} "
                f"(threshold {min_confidence:.0%}) — wrong sold-to may be stamped"
            )
    else:
        warnings.append("customer_confidence not set — verify sold-to manually")

    # ── 3. Sold-to present ────────────────────────────────────────────────────
    if not cust_id:
        issues.append("Sold-to party (customer_number) is blank")

    # ── 4. Ship-to per SO ─────────────────────────────────────────────────────
    for so in sos:
        so_ship  = (so.get("ship_to_id")   or "").strip()
        so_sname = (so.get("ship_to_name") or "").strip()
        so_sorg  = (so.get("sales_organization") or "").strip()
        if so_sorg:
            sorg = so_sorg
        if not so_ship:
            issues.append(
                f"Ship-to ID is blank for SO grouping "
                f"'{so.get('so_grouping_label', '?')}' — cannot create SAP SO"
            )
        elif so_ship == (so.get("sold_to_id") or "").strip():
            warnings.append(
                f"Ship-to ({so_ship}) equals Sold-to — verify this is intentional "
                f"(ship-to name: '{so_sname}')"
            )

    if not sorg:
        issues.append("Sales Organization is blank — cannot route to SAP")

    # ── 5. Line items: materials + quantities + units ─────────────────────────
    total_items    = 0
    unmapped_mats  = []
    zero_qty_items = []
    bad_unit_items = []

    for so in sos:
        for it in so.get("items") or []:
            total_items += 1
            mat_int  = (it.get("internal_material_number") or "").strip()
            mat_ext  = (
                it.get("extracted_material_number")
                or it.get("customer_material_number")
                or it.get("material_description")
                or "?"
            )
            qty_raw  = it.get("quantity")
            unit_raw = (it.get("unit") or "").strip().upper()
            line_no  = it.get("line_number") or "?"

            # Material mapped?
            if not mat_int or mat_int in ("", "None", "nan", "0"):
                unmapped_mats.append(f"Line {line_no}: '{mat_ext}'")

            # Quantity valid?
            try:
                qty = float(str(qty_raw).replace(",", "").strip())
                if qty <= 0:
                    zero_qty_items.append(f"Line {line_no}: qty={qty}")
            except (ValueError, TypeError):
                zero_qty_items.append(f"Line {line_no}: qty='{qty_raw}' (not a number)")

            # Unit known?
            if unit_raw and unit_raw not in VALID_UNITS:
                bad_unit_items.append(f"Line {line_no}: unit='{unit_raw}'")

    if unmapped_mats:
        issues.append(
            f"Unmapped materials ({len(unmapped_mats)}/{total_items} items): "
            + " | ".join(unmapped_mats)
        )
    if zero_qty_items:
        issues.append("Zero/invalid quantity: " + " | ".join(zero_qty_items))
    if bad_unit_items:
        warnings.append(
            "Unrecognised unit (check conversion): " + " | ".join(bad_unit_items)
        )
    if total_items == 0:
        issues.append("No line items found — empty PO or extraction failed")

    # ── Result ────────────────────────────────────────────────────────────────
    status = "FAIL" if issues else ("WARNING" if warnings else "OK")

    return {
        "status":        status,
        "po_number":     po_num,
        "source_file":   src,
        "customer_id":   cust_id,
        "customer_name": cust_nm,
        "ship_to_id":    (sos[0].get("ship_to_id") or "") if sos else "",
        "ship_to_name":  (sos[0].get("ship_to_name") or "") if sos else "",
        "sales_org":     sorg or "",
        "n_sos":         len(sos),
        "n_items":       total_items,
        "n_unmapped":    len(unmapped_mats),
        "confidence":    conf,
        "issues":        issues,
        "warnings":      warnings,
    }


def print_banner(text, width=72, char="="):
    print("\n" + char * width)
    print(f"  {text}")
    print(char * width)


def main():
    parser = argparse.ArgumentParser(
        description="Pre-flight PO validation before SAP Sales Order creation"
    )
    parser.add_argument(
        "--input", "-i", default=DEFAULT_INPUT,
        help=f"Enriched JSONL file (default: {DEFAULT_INPUT})",
    )
    parser.add_argument(
        "--threshold", "-t", type=float, default=MIN_CONFIDENCE,
        help=f"Minimum customer confidence (default: {MIN_CONFIDENCE})",
    )
    parser.add_argument(
        "--json-report", "-j", default="",
        help="Write full JSON report to this file",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"\n[ERROR] Enriched output not found: {input_path}")
        print(
            "\nRun extraction + mapping first, then pre-flight check:\n"
            "  Step 1:  python run_outlook_to_pipeline.py --skip-celonis --dry-run\n"
            "  Step 2:  python preflight_check.py\n"
            "  Step 3:  (if all OK) python run_outlook_to_pipeline.py\n"
        )
        sys.exit(1)

    # ── Load records ──────────────────────────────────────────────────────────
    records = []
    with open(input_path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                pass

    if not records:
        print(f"\n[INFO] No records in {input_path}.")
        sys.exit(0)

    print_banner("PRE-FLIGHT PO VALIDATION REPORT")
    print(f"  File      : {input_path}")
    print(f"  Records   : {len(records)}")
    print(f"  Threshold : confidence >= {args.threshold:.0%}")
    print(f"  Time      : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    results   = [validate_po(r, args.threshold) for r in records]
    ok_list   = [r for r in results if r["status"] == "OK"]
    warn_list = [r for r in results if r["status"] == "WARNING"]
    fail_list = [r for r in results if r["status"] == "FAIL"]

    # ── Summary ───────────────────────────────────────────────────────────────
    print_banner("SUMMARY", char="-")
    print(f"  Total POs checked : {len(results)}")
    print(f"  {color('SAFE TO SUBMIT', SAFE_COLOR):<40} : {len(ok_list)}")
    print(f"  {color('WARNING — review recommended', WARN_COLOR):<40} : {len(warn_list)}")
    print(f"  {color('FAIL — DO NOT SUBMIT', FAIL_COLOR):<40} : {len(fail_list)}")
    if fail_list:
        print(f"\n  {color('!! STOP — fix FAIL items before running pipeline !!', FAIL_COLOR)}")
    elif warn_list:
        print(f"\n  {color('Warnings exist — review and confirm before running', WARN_COLOR)}")
    else:
        print(f"\n  {color('All POs are SAFE — run the pipeline when ready', SAFE_COLOR)}")

    # ── SAFE POs ──────────────────────────────────────────────────────────────
    if ok_list:
        print_banner(f"SAFE TO SUBMIT  ({len(ok_list)} PO(s))", char="-")
        for r in ok_list:
            conf_str = f"{r['confidence']:.0%}" if r["confidence"] is not None else "n/a"
            print(
                f"  {color('[OK]', SAFE_COLOR)}  {r['po_number']:<24}  "
                f"Sold-to: {r['customer_id']}  ({r['customer_name'][:22]})  "
                f"Ship-to: {r['ship_to_id']}  SOrg: {r['sales_org']}  "
                f"Items: {r['n_items']}  Conf: {conf_str}"
            )

    # ── WARNING POs ───────────────────────────────────────────────────────────
    if warn_list:
        print_banner(f"WARNINGS — REVIEW BEFORE RUNNING  ({len(warn_list)} PO(s))", char="-")
        for r in warn_list:
            conf_str = f"{r['confidence']:.0%}" if r["confidence"] is not None else "n/a"
            print(f"\n  {color('[WARN]', WARN_COLOR)} {r['po_number']}  |  {r['source_file']}")
            print(
                f"         Sold-to: {r['customer_id']} ({r['customer_name'][:28]})  "
                f"Ship-to: {r['ship_to_id']}  SOrg: {r['sales_org']}  Conf: {conf_str}"
            )
            for w in r["warnings"]:
                print(f"         {color('⚠', WARN_COLOR)}  {w}")

    # ── FAIL POs ──────────────────────────────────────────────────────────────
    if fail_list:
        print_banner(f"FAILED — WILL ROUTE TO EXCEPTION  ({len(fail_list)} PO(s))", char="-")
        for r in fail_list:
            conf_str = f"{r['confidence']:.0%}" if r["confidence"] is not None else "n/a"
            print(f"\n  {color('[FAIL]', FAIL_COLOR)} {r['po_number']}  |  {r['source_file']}")
            print(
                f"         Sold-to: {r['customer_id']} ({r['customer_name'][:28]})  "
                f"Ship-to: {r['ship_to_id']}  SOrg: {r['sales_org']}  Conf: {conf_str}"
            )
            for issue in r["issues"]:
                print(f"         {color('✗', FAIL_COLOR)}  {issue}")
            for w in r["warnings"]:
                print(f"         {color('⚠', WARN_COLOR)}  {w}")

    print("\n" + "=" * 72)

    # ── JSON report ───────────────────────────────────────────────────────────
    if args.json_report:
        report = {
            "generated_at": datetime.now().isoformat(),
            "input_file":   str(input_path),
            "threshold":    args.threshold,
            "total":        len(results),
            "safe":         len(ok_list),
            "warnings":     len(warn_list),
            "failed":       len(fail_list),
            "results":      results,
        }
        Path(args.json_report).write_text(
            json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        print(f"  JSON report: {args.json_report}")

    sys.exit(1 if fail_list else 0)


if __name__ == "__main__":
    main()
